openapi: 3.0.0
servers:
  - url: https://PROG3_TD2/1.0.0
info:
  version: "latest"
  title: PROG3 - TD2
paths:
  /matches:
    get:
      tags:
        - Match
      summary: get all games
      operationId: getGames
      responses:
        '200':
          description: List of play against
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
        '404':
          description: Error not found

  /teams:
    get:
      tags:
        - Teams
      summary: get all teams
      operationId: getTeams
      responses:
        '200':
          description: List of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
        '400':
          description: error not found
  /players:
    get:
      tags:
        - Player
      summary: get all players
      operationId: getPlayers
      responses:
        '200':
          description: List of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        '400':
          description: error not found

components:
  schemas:
    Match:
      type: object
      properties:
        teams:
          type: array
          minimum: 2
          maximum: 2
          items:
            $ref: '#/components/schemas/Team'
        datetime:
          type: string
          format: date-time
    Team:
      type: object
      properties:
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'
        sponsors:
          type: array
          items:
            $ref: '#/components/schemas/Sponsor'
    Sponsor:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Player:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string